services:
  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
